### ISSUE TITLE
Extend list Pagination

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#46]
Hi!
list-view Pagination is working great , but it has some limitations.
1- You can not specify Row count in it.
2- tiles don't not have auto size, items could also auto size and fill entire area.

right now behavior is this.

![image](https://cloud.githubusercontent.com/assets/11896817/25796242/31cba472-33f2-11e7-8897-992bdf85e508.png)

could it be improved to be like this ?
![image](https://cloud.githubusercontent.com/assets/11896817/25796363/b35abf5a-33f2-11e7-8b6d-063d7bd21777.png)

**Comment by fairygui** [comment]
Workaround for first question is to use bottom-margin.

**Comment by aammfe** [comment]
2- tiles don't not have auto size, items could also auto size and fill entire area.

As you can see in the second image, it has 6 items, and each item’s content is covering whole item area while maintaining aspect ratio and masking any extra item’s content image area. Can you please provide that on priority basis?

**Comment by aammfe** [comment]
Hi!
i hope you are fine, can u plz update about this request ...?

**Comment by fairygui** [comment]
It takes some time..

**Comment by aammfe** [comment]
Just as work around, i m assigning itemRenderer Size at  `ItemGoingToRender`


`main.ListView.itemRenderer = ItemGoingToRender;`

` private void ItemGoingToRender(int index, GObject item)
    {
        var itemRenderer = item as UI_ItemRendererTileView;
        itemRenderer.loader.url = Items[index];


        var height = main.ListView.height / 2 ;
        var width = main.ListView.width / 3;

        if (Mathf.Abs(itemRenderer.width - width) > 0.1f || Mathf.Abs(itemRenderer.height - height) > 0.1f)
        {
            itemRenderer.height = height;
            itemRenderer.width = width;
        }
    }`


this is in Fairy Editor.
![image](https://cloud.githubusercontent.com/assets/11896817/26281122/e5f995e4-3e06-11e7-901d-2cb74d6c89f4.png)


but List is Acting different. 
![image](https://cloud.githubusercontent.com/assets/11896817/26281124/03b9faf6-3e07-11e7-9fb9-f61a14689125.png)

items are overlapping.

**Comment by fairygui** [comment]
Hi, row count feather has been added in editor version 3.1.3 and latest SDK code. Also the overlapping is fixed.

**Comment by aammfe** [comment]
Great but i think adjust item size is still not working ..?
![image](https://cloud.githubusercontent.com/assets/11896817/26442476/101a481a-414e-11e7-80c1-cd98fa425d93.png)


*Edited
![image](https://cloud.githubusercontent.com/assets/11896817/26442526/52fbbc04-414e-11e7-88fb-36a80f1979f7.png)

**Comment by fairygui** [comment]
No, you still need to set width/height in your renderer.

**Comment by aammfe** [comment]
thanx its working , 
looking forward to official pagination auto size support.

**Comment by fairygui** [comment]
Feature already supported.  Issue closed.
